import './assets/style.scss'
import './assets/img/1.png'
import './assets/img/2.png'
import './assets/img/3.png'
import './assets/img/4.png'
import './assets/img/70.png'
import './assets/img/75.png'
import './assets/img/85.png'
import './assets/img/90.png'
import './assets/img/flag.png'
import './assets/img/gear.png'
import './assets/img/logo.png'
import './assets/img/rocket.png'

